### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zhangkch** [ZorionMax/authentication#1]
TypeError: Exception::__construct(): Argument #1 ($message) must be of type string, array given in file /www/wwwroot/api.q1q1.cn/app/Utils/Idcard.php on line 20

#0 /www/wwwroot/api.q1q1.cn/app/Utils/Idcard.php(20): Exception->__construct()
#1 /www/wwwroot/api.q1q1.cn/app/Http/Controllers/IdcardController.php(65): App\Utils\Idcard::verify()
#2 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\IdcardController->index()
#3 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#4 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch()
#5 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\Route->runController()
#6 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\Routing\Route->run()
#7 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#8 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#9 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#10 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(126): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(102): Illuminate\Routing\Middleware\ThrottleRequests->handleRequest()
#12 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(54): Illuminate\Routing\Middleware\ThrottleRequests->handleRequestUsingNamedLimiter()
#13 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\ThrottleRequests->handle()
#14 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#15 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then()
#16 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Router->runRouteWithinStack()
#17 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Routing\Router->runRoute()
#18 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\Routing\Router->dispatchToRoute()
#19 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\Routing\Router->dispatch()
#20 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#21 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#23 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#24 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#26 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#27 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#29 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#31 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\HandleCors->handle()
#33 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()
#35 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then()
#37 /www/wwwroot/api.q1q1.cn/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#38 /www/wwwroot/api.q1q1.cn/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#39 {main}

**Comment by ZorionMax** [comment]
目标源Api失效
